"""
Django settings for Baghyar project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from os.path import dirname, abspath
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = dirname(dirname(dirname(abspath(__file__))))

CONTENT_DIR = os.path.join(BASE_DIR, 'content')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'Customer.middleware.ReadTokenFromBodyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Baghyar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(CONTENT_DIR, 'templates'),
            os.path.join(BASE_DIR, 'env/lib/python3.7/site-packages/django/contrib/admin/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Baghyar.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S",
    'DATE_FORMAT': "%Y-%m-%d",
    'DATETIME_INPUT_FORMATS': "%Y-%m-%d %H:%M:%S",
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '2000/day',
        'user': '10000/day'
    },
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(CONTENT_DIR, 'static')
STATIC_URL = '/static_files/'

MEDIA_ROOT = os.path.join(CONTENT_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(CONTENT_DIR, 'assets'),
]


MAX_SPOUT_QUANTITY = 10

DEVICE_CONNECTION_LOG_MINUTES = 5
DEVICE_DELAY_TO_ACTION_DEFAULT_SECONDS = 18

MAX_PROGRAM_FOR_LAND = 30

PROGRAM_NEW_ID_FROM = 10

DEFAULT_LONGITUDE = 51.388721
DEFAULT_LATITUDE = 35.728954
DEFAULT_LOCATION = 'Tehran'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

IRRIGATION_UPDATE_DELAY = datetime.timedelta(minutes=1)

PHONE_NUMBER_REGEX = '^(0098|\+98|0)?9\d{9}$'

SPECTACULAR_DEFAULTS = {
    'SCHEMA_PATH_PREFIX': r'^panel/api/u|d/',
}

SPECTACULAR_SETTINGS = {
    'SCHEMA_PATH_PREFIX': r'^panel/api/u|d/',
}

LOG_DEBUGS = False
